### ISSUE TITLE
 INIT_CODE solidity

### ISSUE THREAD

**Issue by luoqeng** [bitbankinc/exchangeDepositContract#24]
Can you provide INIT_CODE solidity implementation version for easy understanding and maintenance?

**Comment by junderw** [comment]
There is no solidity.

It was written in EVM bytes directly.

This is an (about) equivalent version in Solidity.

https://github.com/bitbankinc/exchangeDepositContract/blob/bd2cf30bebaec4b6c0bd1778ef5bc3c511f78f74/contracts/ExchangeDeposit.sol#L312-L352

**Comment by junderw** [comment]
But tbh, this explanation is very VERY in depth as to exactly how the proxy works.

It has been audited by ConsenSys.

https://github.com/bitbankinc/exchangeDepositContract/blob/130d066ffa709f4a1464d4eaff4c17cf3bb43ce2/contracts/ProxyFactory.sol#L55-L134

**Comment by junderw** [comment]
ConsenSys audit results:

https://consensys.net/diligence/audits/2020/11/bitbank/

**Comment by junderw** [comment]
This is a comparison of the latest master commit with the commit that the audit mentions.

https://github.com/bitbankinc/exchangeDepositContract/compare/3daeedb029ef4642e82550a24726875675284bb3...130d066ffa709f4a1464d4eaff4c17cf3bb43ce2

**Comment by junderw** [comment]
You can ignore the README changes and for_testing folder contract changes.

Just look at the actual contracts. There were 2 formatting changes (whitespace) and I changed the mainAddress from private to public. Which has nothing to do with the INIT_CODE

**Comment by junderw** [comment]
Using a Solidity Proxy costs an extra 117% in gas to deploy.
Per-user cost of deploying would rise from around 67k gas to around 145k gas.

So if you have 60k users, and pay an average of 60 gwei and 1 ETH = $3,254.76

67k gas -> $785,048.11
145k gas -> $1,698,984.72

This is primarily why we chose to write the proxy using EVM bytes directly and had Consensys audit it.

We saved 100s of thousands of dollars, and the audit didn't cost nearly that much.

If you find an issue with the binary proxy, please let us know and we will reward anyone through our bug bounty program.

https://bugbounty.jp/program/qb8PhPWbO1FZvf74ds8cgjNg
